export const EMPLOYEE_LOGIN_REQUEST="EMPLOYEE_LOGIN_REQUEST"
export const EMPLOYEE_LOGIN_SUCCESS="EMPLOYEE_LOGIN_SUCCESS"
export const EMPLOYEE_LOGIN_FAIL="EMPLOYEE_LOGIN_FAIL"
export const EMPLOYEE_LOGOUT="EMPLOYEE_LOGOUT"

export const EMPLOYEE_REGISTER_REQUEST='EMPLOYEE_REGISTER_REQUEST'
export const EMPLOYEE_REGISTER_SUCCESS='EMPLOYEE_REGISTER_SUCCESS'
export const EMPLOYEE_REGISTER_FAIL= 'EMPLOYEE_REGISTER_FAIL'

export const EMPLOYEE_DETAIL_REQUEST='EMPLOYEE_DETAIL_REQUEST'
export const EMPLOYEE_DETAIL_SUCCESS='EMPLOYEE_DETAIL_SUCCESS'
export const EMPLOYEE_DETAIL_FAIL=   'EMPLOYEE_DETAIL_FAIL'
export const EMPLOYEE_DETAIL_RESET = 'EMPLOYEE_DETAILS_RESET'

export const EMPLOYEE_UPDATE_PROFILE_REQUEST ='EMPLOYEE_UPDATE_PROFILE_REQUEST'
export const EMPLOYEE_UPDATE_PROFILE_SUCCESS ='EMPLOYEE_UPDATE_PROFILE_SUCCESS'
export const EMPLOYEE_UPDATE_PROFILE_FAIL = 'EMPLOYEE_UPDATE_PROFILE_FAIL'
export const EMPLOYEE_UPDATE_PROFILE_RESET ='EMPLOYEE_UPDATE_PROFILE_RESET'

export const EMPLOYEE_DELETE_REQUEST='EMPLOYEE_DELETE_REQUEST'
export const EMPLOYEE_DELETE_SUCCESS='EMPLOYEE_DELETE_SUCCESS'
export const EMPLOYEE_DELETE_FAIL   =   'EMPLOYEE_DELETE_FAIL'
export const EMPLOYEE_DELETE_RESET  = 'EMPLOYEE_DELETE_RESET'