export const CANDIDATE_LOGIN_REQUEST="CANDIDATE_LOGIN_REQUEST"
export const CANDIDATE_LOGIN_SUCCESS="CANDIDATE_LOGIN_SUCCESS"
export const CANDIDATE_LOGIN_FAIL="CANDIDATE_LOGIN_FAIL"
export const CANDIDATE_LOGOUT="CANDIDATE_LOGOUT"

export const CANDIDATE_REGISTER_REQUEST='CANDIDATE_REGISTER_REQUEST'
export const CANDIDATE_REGISTER_SUCCESS='CANDIDATE_REGISTER_SUCCESS'
export const CANDIDATE_REGISTER_FAIL=   'CANDIDATE_REGISTE'

export const CANDIDATE_DETAIL_REQUEST='CANDIDATE_DETAIL_REQUEST'
export const CANDIDATE_DETAIL_SUCCESS='CANDIDATE_DETAIL_SUCCESS'
export const CANDIDATE_DETAIL_FAIL=   'CANDIDATE_DETAIL_FAIL'
export const CANDIDATE_DETAIL_RESET = 'CANDIDATE_DETAILS_RESET'

export const CANDIDATE_UPDATE_PROFILE_REQUEST ='CANDIDATE_UPDATE_PROFILE_REQUEST'
export const CANDIDATE_UPDATE_PROFILE_SUCCESS ='CANDIDATE_UPDATE_PROFILE_SUCCESS'
export const CANDIDATE_UPDATE_PROFILE_FAIL = 'CANDIDATE_UPDATE_PROFILE_FAIL'
export const CANDIDATE_UPDATE_PROFILE_RESET ='CANDIDATE_UPDATE_PROFILE_RESET'

export const CANDIDATE_DELETE_REQUEST='CANDIDATE_DELETE_REQUEST'
export const CANDIDATE_DELETE_SUCCESS='CANDIDATE_DELETE_SUCCESS'
export const CANDIDATE_DELETE_FAIL=   'CANDIDATE_DELETE_FAIL'
export const CANDIDATE_DELETE_RESET = 'CANDIDATE_DELETE_RESET'