export const JOB_LIST_REQUEST='JOB_LIST_REQUEST'
export const JOB_LIST_SUCCESS='JOB_LIST_SUCCESS'
export const JOB_LIST_FAIL='JOB_LIST_FAIL'

export const POST_JOB_REQUEST='POST_JOB_REQUEST'
export const POST_JOB_SUCCESS='POST_JOB_SUCCESS'
export const POST_JOB_FAIL='POST_JOB_FAIL'
export const POST_JOB_RESET='POST_JOB_RESET'


export const EMPLOYER_JOB_LIST_REQUEST='EMPLOYER_JOB_LIST_REQUEST'
export const EMPLOYER_JOB_LIST_SUCCESS='EMPLOYER_JOB_LIST_SUCCESS'
export const EMPLOYER_JOB_LIST_FAIL='EMPLOYER_JOB_LIST_FAIL'

export const EMPLOYER_JOB_DETAIL_REQUEST='EMPLOYER_JOB_DETAIL_REQUEST'
export const EMPLOYER_JOB_DETAIL_SUCCESS='EMPLOYER_JOB_DETAIL_SUCCESS'
export const EMPLOYER_JOB_DETAIL_FAIL='EMPLOYER_JOB_DETAIL_FAIL'

export const EMPLOYER_JOB_UPDATE_REQUEST='EMPLOYER_JOB_UPDATE_REQUEST'
export const EMPLOYER_JOB_UPDATE_SUCCESS='EMPLOYER_JOB_UPDATE_SUCCESS'
export const EMPLOYER_JOB_UPDATE_FAIL='EMPLOYER_JOB_UPDATE_FAIL'

export const EMPLOYER_JOB_DELETE_REQUEST='EMPLOYER_JOB_DELETE_REQUEST'
export const EMPLOYER_JOB_DELETE_SUCCESS='EMPLOYER_JOB_DELETE_SUCCESS'
export const EMPLOYER_JOB_DELETE_FAIL='EMPLOYER_JOB_DELETE_FAIL'



